import {TCoilShape, TElectricParam, TNumbArr, TWire} from './states'

export enum TSourceDataActionTypes {
  //Wire
  CHANGE_WIRE = 'CHANGE_WIRE',
  CHANGE_ISOLATION = 'CHANGE_ISOLATION',
  //Coil
  CHANGE_SHAPE = 'CHANGE_SHAPE',
  TOGGLE_COIL_TYPE = 'TOGGLE_COIL_TYPE',
  CHANGE_MAX_HEIGHT = 'CHANGE_MAX_HEIGHT',
  CHANGE_MAX_THICK = 'CHANGE_MAX_THICK',
  CHANGE_INNER_LENGTH = 'CHANGE_INNER_LENGTH',
  CHANGE_TURNS = 'CHANGE_TURNS',
  CHANGE_FILL_PCT = 'CHANGE_FILL_PCT',
  //Supply
  TOGGLE_FORCING = 'TOGGLE_FORCING',
  CHANGE_HOLD_VOLTAGE = 'CHANGE_HOLD_VOLTAGE',
  CHANGE_FORCE_VOLTAGE = 'CHANGE_FORCE_VOLTAGE',
  CHANGE_VOLTAGE_DEV = 'CHANGE_VOLTAGE_DEV',
  //Temp
  CHANGE_OVERHEAT = 'CHANGE_OVERHEAT'
}

export enum TFinalDataActionTypes {
  //Coil
  CHANGE_HEIGHT = 'CHANGE_HEIGHT',
  CHANGE_THICK = 'CHANGE_THICK',
  CHANGE_AVG_TURN_LENGTH = 'CHANGE_AVG_TURN_LENGTH',
  CHANGE_WEIGHT = 'CHANGE_WEIGHT',
  //Resist
  CHANGE_RESIST_WITHOUT_OVERHEAT = 'CHANGE_RESIST_WITHOUT_OVERHEAT',
  CHANGE_RESIST_WITH_OVERHEAT = 'CHANGE_RESIST_WITH_OVERHEAT',
  //Electric params with hold voltage
  CHANGE_ELECTRIC_PARAMS_WITHOUT_OVERHEAT_HOLD_VOLTAGE = 'CHANGE_ELECTRIC_PARAMS_WITHOUT_OVERHEAT_HOLD_VOLTAGE',
  CHANGE_ELECTRIC_PARAMS_WITH_OVERHEAT_HOLD_VOLTAGE = 'CHANGE_ELECTRIC_PARAMS_WITH_OVERHEAT_HOLD_VOLTAGE',
  //Electric params with force voltage
  CHANGE_ELECTRIC_PARAMS_WITHOUT_OVERHEAT_FORCE_VOLTAGE = 'CHANGE_ELECTRIC_PARAMS_WITHOUT_OVERHEAT_FORCE_VOLTAGE',
  CHANGE_ELECTRIC_PARAMS_WITH_OVERHEAT_FORCE_VOLTAGE = 'CHANGE_ELECTRIC_PARAMS_WITH_OVERHEAT_FORCE_VOLTAGE',
}

export type TSourceDataAction = {
  type: TSourceDataActionTypes,
  wire?: TWire,
  shape?: TCoilShape,
  value?: number
}

export type TFinalDataAction = {
  type: TFinalDataActionTypes,
  value?: number,
  resist?: TNumbArr,
  params?: TElectricParam
}